# 应用服务 WEB 访问端口
server:
  port: 80

spring:
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/spring?serverTimezone=UTC
      username: root
      password: 123456

mybatis-plus:
  global-config:
    db-config:
      table-prefix: tsl_
      id-type: auto
  configuration:
    # 配置控制台输出sql信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

